### ISSUE TITLE
First time bonus bug

### ISSUE THREAD

**Issue by MarlonWelter** [lmachens/trophy-hunter#78] opened 2019-01-14 10:45 UTC
According to our discord, the trophy siege master was achieved for the first time, but the bonus wasn't given.

**Comment by lmachens** [comment] 2019-01-14 20:36
I can approve it. 
He obtained the trophy for the first time and didn't get the first time bonus:
![image](https://user-images.githubusercontent.com/10058950/51139550-7cabfe00-1844-11e9-821f-51be0d503618.png)

**Comment by lmachens** [comment] 2019-01-14 20:55
Can not reproduce. I guess it is because of the server issues we had last weekend.
Close it for now.

**Closed by lmachens** 2019-01-14 20:55 UTC
